name: Release Image

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version of release image'
        required: true
        default: ''
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.ref_name }}


permissions:
  contents: 'read'
  id-token: 'write'

run-name: release image ${{ inputs.release_version }} ${{ github.ref_name }}

jobs:
  release-version:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_relese_version.outputs.release_version }}
    steps:
      - name: Get Release Version
        id: get_relese_version
        run: |
          RELEASE_VERSION=${{ inputs.release_version }}
          if [ -z "$RELEASE_VERSION" ]; then
              RELEASE_VERSION=${{ env.RELEASE_VERSION }}
          fi
          echo release_version=$RELEASE_VERSION >> $GITHUB_OUTPUT

  release-image:
    needs: release-version
    uses: apecloud-inc/apecloud-cd/.github/workflows/release-image-cache.yml@v0.2.0
    with:
      IMG: "apecloud/tpcds"
      VERSION: "${{ needs.release-version.outputs.release-version }}"
      DOCKERFILE_PATH: "./dockerfile"
      APECD_REF: "v0.2.0"
    secrets: inherit
